Table posts {
  id int [pk, increment]
  title varchar(250)
  details varchar(250) [not null, default: '']
  created_at timestamptz [default: `now()`, not null]
  updated_at timestamptz [default: `now()`, not null]
  created_by int
}

Table users {
  id int [pk, increment]
  created_at timestamptz [default: `now()`, not null]
  updated_at timestamptz [default: `now()`, not null]
  email varchar(250) [unique, not null]
  password varchar(250) [not null]
  last_signed_in_at timestamptz
}

Ref: posts.created_by > users.id